services:
  # 1. База даних
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: analytics_db
    ports:
      - "5432:5432"
    networks:
      - martech-net
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d analytics_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Брокер повідомлень NATS
  nats:
    image: nats:latest
    ports:
      - "4222:4222" # Основний порт для клієнтів
      - "8222:8222" # Моніторинг (http://localhost:8222)
    networks:
      - martech-net

  # 3. Наш додаток (Backend)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # Підключення до БД (зверніть увагу, host = ім'я сервісу 'postgres')
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/analytics_db
      # Підключення до NATS (host = ім'я сервісу 'nats')
      NATS_URL: nats://nats:4222
    depends_on:
      postgres:
        condition: service_healthy # <--- МАГІЯ ТУТ
      nats:
        condition: service_started
    networks:
      - martech-net

  # 4. Генератор подій (з завдання)
  event-publisher:
    image: andriiuni/events
    environment:
      # Вказуємо куди слати події. 'app' - це ім'я нашого сервісу вище.
      EVENT_ENDPOINT: http://app:3000/webhook
    depends_on:
      - app
    networks:
      - martech-net
      
# 5. Адмінка для БД (pgAdmin)
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - martech-net

networks:
  martech-net:

volumes:
  pgdata:
